### ISSUE TITLE
Mod compatibility with Pain in the Glass

### ISSUE THREAD

**Issue by HopsandBarley** [LordGrimmauld/windowlogging#15]
I have both Pain in the Glass and Windowlogging installed.  

Pain in the Glass gives you the flexibility to place Panes on 'edges' and 'corners' of blocks, rather than always in the middle. 

When i try to 'windowlog' PITG panes, the do not render in the game.  they are invisible.  

I don't know if this is a problem with PITG or Windowlogging, so I'm putting this comment in both places.  Thanks!  Two really nice and creative mods.

**Comment by MongoTheElder** [comment]
Hi! I'm the author of Pane In The Glass (PITG). The underlying issue is I use the _forge:glass_pane_ tag so my panes can be used in crafting recipes but they are not compatible with your mod. PITG panes are not derived from either _PaneBlock_ or _FourWayBlock_ and require blockstates to determine which orientation to render.

Is there a way you can add a test to make sure the pane block is derived from _FourWayBlock_ as a secondary way to filter out non-compatible blocks?

**Comment by LordGrimmauld** [comment]
I implemented a simple instanceof, this should be fine now
